[tool.poetry]
name = "movieparse"
version = "0.1.0"
description = ""
authors = ["schuenemann"]

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.64.1"
pandas = "^1.5.1"
requests = "^2.28.1"
pathlib = "^1.0.1"
numpy = "^1.23.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
movieparse = "movieparse.cli:main"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
